# pages/weekly_impact_report.py
import streamlit as st
import pandas as pd

def render(master_df, notion_df):
    total_actions = len(notion_df) if not notion_df.empty else 0
    edited_clicks = 0
    edited_impressions = 0
    merged_impact = pd.DataFrame()

    if not notion_df.empty and not master_df.empty:
        impact_df = notion_df.copy()
        impact_df["Clean_URL"] = (
            impact_df["Page / URL"]
            .str.replace("https://www.shreeshivam.com", "", regex=False)
            .str.replace("https://shreeshivam.com", "", regex=False)
            .str.rstrip("/")
            .str.lower()
        )

        merged_impact = pd.merge(
            impact_df,
            master_df,
            left_on="Clean_URL",
            right_on="URL",
            how="inner",
        )

        if not merged_impact.empty:
            edited_clicks = int(merged_impact["Clicks"].sum()) if "Clicks" in merged_impact.columns else 0
            edited_impressions = int(merged_impact["Impressions"].sum()) if "Impressions" in merged_impact.columns else 0

    st.markdown(
        """
        <style>
        .proof-box {
            background: linear-gradient(135deg, rgba(46,204,113,.11), rgba(77,168,179,.06));
            border: 1px solid rgba(46,204,113,.22);
            border-radius: 14px;
            padding: 25px;
            margin-bottom: 25px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            flex-wrap: wrap;
            gap: 20px;
        }
        .proof-text h2 { margin: 0 0 8px 0; color: #2ecc71; font-size: 1.8rem; font-weight: 900; }
        .proof-text p { margin: 0; color: #a09f98; max-width: 600px; font-size: 14px; }
        .proof-stat { text-align: center; min-width: 120px; }
        .proof-val { font-size: 2.5rem; font-weight: 900; line-height: 1; }
        .proof-lbl { font-size: 10px; text-transform: uppercase; letter-spacing: 1px; color: #78766c; margin-top: 4px; }
        .kpi-card {
            background: #111009;
            border: 1px solid #2e2b26;
            padding: 15px 20px;
            border-radius: 10px;
            border-top: 3px solid #2ecc71;
        }
        .kpi-card.blue { border-top: 3px solid #4da8b3; }
        .kpi-val { font-size: 2rem; font-weight: 900; color: white; line-height: 1.2; }
        .kpi-lbl { font-size: 11px; text-transform: uppercase; color: #78766c; letter-spacing: 1px; margin-bottom: 5px; }
        .badge-green { background: rgba(46,204,113,.1); color: #2ecc71; padding: 4px 10px; border-radius: 4px; font-size: 10px; text-transform: uppercase; border: 1px solid rgba(46,204,113,.2); font-weight: bold; margin-right: 8px; }
        .badge-blue { background: rgba(77,168,179,.1); color: #4da8b3; padding: 4px 10px; border-radius: 4px; font-size: 10px; text-transform: uppercase; border: 1px solid rgba(77,168,179,.2); font-weight: bold; }
        </style>
        """,
        unsafe_allow_html=True,
    )

    st.markdown(
        f"""
        <div>
            <span class="badge-green">🌱 Green Shoots Mode</span>
            <span class="badge-blue">100% API Verified</span>
        </div>
        <h1 style="margin: 15px 0 5px 0; font-size: 2.8rem; font-weight: 900; line-height: 1.1;">
            Shree Shivam <em style="color: #2ecc71; font-style: normal;">Weekly SEO Sprint</em>
        </h1>
        <p style="color: #78766c; font-size: 13px; margin-bottom: 25px;">
            Source: Google Search Console (live) &bull; Change log: Notion SEO tracker
        </p>
        """,
        unsafe_allow_html=True,
    )

    st.markdown(
        f"""
        <div class="proof-box">
            <div class="proof-text">
                <h2>Direct Impact of Manual SEO Edits</h2>
                <p>
                    These numbers represent the live Google traffic specifically generated by the
                    <strong>{total_actions} URLs</strong> modified in our Notion SEO Tracker during this sprint.
                    This proves direct ROI on engineering time.
                </p>
            </div>
            <div style="display: flex; gap: 30px; flex-wrap: wrap;">
                <div class="proof-stat">
                    <div class="proof-val" style="color: #2ecc71;">{edited_clicks:,}</div>
                    <div class="proof-lbl">Clicks Generated</div>
                </div>
                <div class="proof-stat">
                    <div class="proof-val" style="color: #4da8b3;">{edited_impressions:,}</div>
                    <div class="proof-lbl">New Impressions</div>
                </div>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

    st.markdown(
        "<h3 style='font-size: 14px; text-transform: uppercase; letter-spacing: 1px; color: #78766c; margin-bottom: 15px;'>Sprint Scoreboard</h3>",
        unsafe_allow_html=True,
    )

    total_site_clicks = int(master_df["Clicks"].sum()) if "Clicks" in master_df.columns else 0
    total_site_imp = int(master_df["Impressions"].sum()) if "Impressions" in master_df.columns else 0

    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.markdown(
            f"""<div class="kpi-card"><div class="kpi-lbl">Actions Logged</div><div class="kpi-val">{total_actions}</div></div>""",
            unsafe_allow_html=True,
        )
    with col2:
        st.markdown(
            f"""<div class="kpi-card blue"><div class="kpi-lbl">Total Site Clicks</div><div class="kpi-val">{total_site_clicks:,}</div></div>""",
            unsafe_allow_html=True,
        )
    with col3:
        st.markdown(
            f"""<div class="kpi-card"><div class="kpi-lbl">Total Impressions</div><div class="kpi-val">{total_site_imp:,}</div></div>""",
            unsafe_allow_html=True,
        )
    with col4:
        st.markdown(
            """<div class="kpi-card blue"><div class="kpi-lbl">Sprint Hours</div><div class="kpi-val">40</div></div>""",
            unsafe_allow_html=True,
        )

    st.write("---")
    st.subheader("✅ Actions Completed & Impact")

    if not notion_df.empty and not merged_impact.empty:
        display_cols = ["Date", "Page / URL", "Notes / Action"]
        if "Clicks" in merged_impact.columns:
            display_cols.append("Clicks")
        if "Impressions" in merged_impact.columns:
            display_cols.append("Impressions")

        report_table = merged_impact[display_cols].copy()

        if "Clicks" in report_table.columns:
            report_table["Clicks"] = report_table["Clicks"].astype(int)
        if "Impressions" in report_table.columns:
            report_table["Impressions"] = report_table["Impressions"].astype(int)

        if "Clicks" in report_table.columns:
            report_table = report_table.sort_values(by="Clicks", ascending=False)

        st.dataframe(report_table, width="stretch", height=400)
    else:
        st.info("Log SEO edits in Notion to see their direct traffic impact here.")